-- Supabase SQL for messages table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_username text not null,
  receiver_username text not null,
  message text not null,
  created_at timestamptz not null default now(),
  read boolean not null default false,
  reply text
);

-- Index for fast lookup by receiver
create index if not exists idx_receiver_username on messages(receiver_username);

-- (Optional) Only allow receiver to select their messages
-- (You can add RLS policies in Supabase dashboard)
